azure:
  app:
    config:
      endpoint: ${APP_CONFIG_ENDPOINT}
      label:
        global: service-discovery

app:
  secrets:
    keycloak-domain: aca-cross-keycloak-ms-uri
    issuer-domain: aca-issuer-vci-ms-uri
    authentic-sources-domain: aca-issuer-auth-src-ms-uri
    key-vault-domain: key-vault-uri
    remote-signature-domain: aca-cross-rmt-sign-ms-uri
    keycloak-did: issuer-keycloak-did
    issuer-did: issuer-info-id-did
